# Generated by Django 4.1.3 on 2022-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todolistitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
